name: Tests

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Print run info
        run: |
          echo "GitHub event: $GITHUB_EVENT_NAME"
          echo "node version: $(node --version)"
          echo "npm version: $(npm --version)"
      - name: Install dependencies
        run: npm ci
      - run: npm run lint:lint
      - run: npm run lint:types
      - run: npm run lint:format
      - run: npm test
        # We don't have any tests on the built site right now,
        # we're just confirming that there are no errors running the build
      - run: npm run build
